### ISSUE TITLE
 ImportError: cannot import name Transformation in Python Rules

### ISSUE THREAD

**Issue by tamtam1111** [openhab/openhab-core#3228]
Hi,
after updating to 3.4 M6 I noticed multiple Import Errors in my Python Rules:
`2022-12-13 19:22:32.582 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/python/personal/entryMotion.py': ImportError: cannot import name Transformation in /openhab/conf/automation/jsr223/python/personal/entryMotion.py at line number 4` which come from "from core.actions import Transformation". 

I suspect that something has changed in the Transformation Service and now needs to be adjusted in the Python libraries?

**Comment by J-N-K** [comment]
I'm not familiar with python, can you shortly describe what I need to do to reproduce the issue?

**Comment by tamtam1111** [comment]
Sure, but unfortunately there are a few steps involved. You must install the Helper Libraries according to [this instructions](https://community.openhab.org/t/ivan-s-helper-libraries-oh3-python-javascript/116458). Then you can add a python script like this /openhab/conf/automation/jsr223/python/personal/hello_world.py with `from core.actions import Transformation` as content. I hope this will reproduce the error.
